[project]
name = "clump-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vdbma" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5"
]

[project.scripts]
clump-tracker = "clump_tracker:main"

[tool.maturin]
module-name = "clump_tracker._core"
python-packages = ["clump_tracker"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
testing = [
    "pytest>=9.0.1",
]

[tool.pytest]
strict = true
filterwarnings = ["error"]
